### ISSUE TITLE
make install step breaks with error "malformed #cgo argument"

### ISSUE THREAD

**Issue by borisdev** [rgburke/grv#26]
```
$go get -d github.com/rgburke/grv/cmd/grv
$cd $GOPATH/src/github.com/rgburke/grv
$make install
```

returns this error

```
[100%] Built target git2
go install -tags static ./...
can't load package: package gopkg.in/libgit2/git2go.v25: /Users/boris/.gvm/pkgsets/go1.4/global/src/gopkg.in/libgit2/git2go.v25/git_static.go: malformed #cgo argument: -I${SRCDIR}/vendor/libgit2/include
make[1]: *** [install-static] Error 1
make: *** [build-libgit2] Error 2
```

**Comment by rgburke** [comment]
Thanks for reporting this issue. I was able to reproduce the same error when using go 1.4. I was able to successfully compile GRV using go version 1.5.

Therefore this looks like a go version 1.4 issue which has since been fixed. All I can suggest is to upgrade to a newer version of go (1.5 or later). I have updated the README to say that at least go 1.5 is required to compile GRV.
