### ISSUE TITLE
grv just got killed right after it started

### ISSUE THREAD

**Issue by lmesz** [rgburke/grv#37]
Hello,

I wanted to try out your tool but after I clone the repo and execute make install and trying to run grv the process just got killed without any sign.

```
[1]    13812 killed     ggui
```
I compiled with the following command: `make install BINARY=ggui`
The binary setting is irrelevant since it shows the same symptoms when I just fire a make install.
What am I doing wrong and how can I make it work? Also what else information do you need for this?

Thanks

**Comment by rgburke** [comment]
Thanks for reporting this issue. In order to try and track down what the issue might be I've got a few questions:

- When you run `ggui` are you simply doing: `$ ggui`? Or do you pass in any command line arguments?
- Is there anything printed when GRV is killed?
- Does `ggui` immediately die? Does any part of the normal UI appear?
- Are you running `ggui` within a git repository or from outside a git repository?

To help debug this could you try:

- Let us know which system you're on and which go version you're using. 
- Run `ggui` with logging set to `DEBUG`. e.g. `ggui -logLevel DEBUG` and attach the log file here.
- Run `ggui` under GDB and report what happends. e.g. `gdb -ex=r ggui`.

If there's anything else you notice that might also help explain the issue you're seeing then please feel free to mention it.

**Comment by lmesz** [comment]
- When you run `ggui` are you simply doing: `$ ggui`? Or do you pass in any command line arguments? - Yes just simply ggui without cli arguments, cause the `$GOPATH/bin` is on my PATH.
- Is there anything printed when GRV is killed? - No, just the pasted kill message.
- Does `ggui` immediately die? Does any part of the normal UI appear? - No, nothing it just got killed immediately.
- Are you running ggui within a git repository or from outside a git repository? - Tried both and got the same result.

- Some system information: MacOS Sierra 10.12.6 go version: go version go1.8 darwin/amd64
- Run ggui with logging set to DEBUG. e.g. ggui -logLevel DEBUG and attach the log file here. - Also got killed without log file.
- Ok will run ggui with gdb tomorrow.

Thanks for the fast response.

**Comment by rgburke** [comment]
@lmesz Could you install GRV using homebrew and see if you still have this issue?

**Comment by lmesz** [comment]
No need for this. I just update my local workspace and it starts after compile. I think the libgit update solved the issue but not sure.
