### ISSUE TITLE
Remap "Show actions for commit" to a key other than <C-a>

### ISSUE THREAD

**Issue by marcelpaulo** [rgburke/grv#57]
Is it possible to remap `Show actions for commit` to another key other than `<C-a>` ? `<C-a>` is a popular key combination for the tmux prefix. I couldn't find something that resembled `Show actions for commit` in the [documentation](https://github.com/rgburke/grv/blob/master/doc/documentation.md), perhaps I didn't look properly.

**EDIT**: I forgot to mention: I'm running grv ff99964 on Xubuntu 18.04.

**Comment by rgburke** [comment]
Yes, `Show actions ...` can be remapped using the key string `<grv-show-available-actions>`. So to use
`<C-n>` instead for example:
```
map All <C-n> <grv-show-available-actions>
```

I'm afraid the documentation is slightly out of date at the moment and doesn't contain some of the latest key bindings and features added. 

Ideally #32 needs to be implemented so that the documentation is available from within grv. This would ensure it's always correct for the version used and some information such as key bindings could be auto-generated.

Another step we can take is to change the default key binding, as I imagine other tmux or screen users will also run into this. Do you have any thoughts or objections if I change the `Show actions ...` key binding to `<C-n>`?

**Comment by marcelpaulo** [comment]
> Yes, Show actions ... can be remapped using the key string `<grv-show-available-actions>`

I've just done it, great, thanks for the tip ! 

> Ideally #32  needs to be implemented so that the documentation is available from within grv

This would be ideal ! Or, if that's too much trouble to implement, perhaps include it in the `--help` command line option.

> Do you have any thoughts or objections if I change the Show actions ... key binding to <C-n>?

I think it's a good default. I get the impression tmux/screen prefix keys tend to be within easy reach of the Right-Ctrl key so that you can type it with one single hand, and `<C-n>` is quite far away. And it's not one of the usual terminal emulator shortcuts for managing tabs, so no clash there either.

> some information such as key bindings could be auto-generated

I've noticed that, even though I bound `<grv-show-available-actions>` to `<C-n>`, and it's working, the status line still shows the current default key binding `<C-a>`. Auto-generating info about the key bindings would also cover that ? Would you like me to open an issue to track this ? Perhaps it's already in your roadmap.

**Comment by rgburke** [comment]
Thanks for the feedback. As you mentioned the status bar only shows default key bindings at the moment, it's not dynamic. So please do open an issue, it's something that should be fixed.
