### ISSUE TITLE
Limit the number of commits in list

### ISSUE THREAD

**Issue by colonelchlorine** [rgburke/grv#73]
Working on a repo that has 80,000 commits it takes a long time to launch grv. Switching branches in the History View is not too slow, but could have a lag because of the number of commits.

I'm usually not ever interested in any commits older than a year, so is there a configuration option that would limit the # of commits grv loads/displays?

Running on Windows using the linux subsystem.

Edit: Awesome program by the way. Thanks!

**Comment by rgburke** [comment]
Thanks for raising this. GRV doesn't currently have an option for limiting the number of commits that are loaded. This is something that definitely needs to be added, especially as repositories like linux will eventually have millions of commits.

Adding a configuration variable called `commitLimit` would be one option. This variable could be set to a numeric limit:
```
set commitLimit 10000
```
Another option is to also allow this variable to be set to a duration from now into the past. For example:
```
set commitLimit "18 months"
```
This is a bit tougher as commits don't necessarily appear in chronological order (due to merging, rebasing, etc...). So it would probably have to stop loading commits after the first commit older than the duration is found.

Does that sound like an approach that would be useful?

I will also have a look into the start up of GRV to work out where the time is being spent.

**Comment by colonelchlorine** [comment]
Both of those configurations sound good. You're right - dates are tricky with git, but your suggestion makes sense (stop as soon as commit is > date). I remember in gitk, I used to use the "since" configuration. Think it takes an ISO format date, even shortened (2018-05-01).

Another idea is a ref to stop at. Could be useful in version tags. `set commitLimit v1.2.0`?

**Comment by rgburke** [comment]
Yeah, that's a nice idea. Let's say then that the value of `commitLimit` can be one of the following:
 - Numeric value (e.g. `10000`)
 - Date (e.g. `2018-07-06`, `2018-07-06 22:00:00`, `2018-07-06 22:00:00+0100`)
 - Tag or commit ID (e.g. `v1.2.3`, `1e542d0`)

I did have a look into parsing durations (e.g. `6 months 15 days`) with go but the standard library is limited to units of hours and less. There don't seem to be any other good libraries out there for handling durations. So we'll have to leave out duration strings for the moment.

**Comment by rgburke** [comment]
A `commit-limit` config variable has been added to GRV which accepts the values described above. A few optimisations have also been made to improve the startup time of GRV:
 - `git status` is now loaded asychronously. GRV would previously block until this was loaded on startup.
 - Refs are now displayed sooner. GRV would previously load the commit for each tag (expensive for repo's like Linux with > 500 tags) before all refs were shown, this is also now done asynchronously.

These improvements combined with the `commit-limit` should make GRV quicker to start up and use fewer resources. One caveat is that commit loading is still quite slow. This is due to an issue with libgit2 walking the entire history unnecessarily for unsorted output (like `git log`). It's fixed by libgit2/libgit2#4606 but this fix isn't released yet. When this fix is released in the commit loading speed of GRV should be pretty good. For example, the gif below shows GRV (using master libgit2) loading the first 100,000 commits from the Linux repo in about 5 seconds when running in an Ubuntu VM on a HDD:

![commit-load](https://user-images.githubusercontent.com/7596018/42728861-442c7da6-87bd-11e8-896b-dd173854ed78.gif)

But this is a demo of what the future performance could be, it is not available yet.

**Comment by colonelchlorine** [comment]
That's awesome! Good to hear the libgit2 improvements are also coming.

Is this near a tag/release state for grv? I tried to clone the repo and build with Go, but I haven't done that in a long while so my Windows 10 bash isn't hooked up yet.

Thanks again. I guess this issue can be resolved?

**Comment by rgburke** [comment]
A build made from the latest code on master is available here: [grv_v0.2.0-23_linux64.gz](https://github.com/rgburke/grv/files/2215205/grv_v0.2.0-23_linux64.gz) (I had to gzip it to attach it to a comment)

If you're happy that the `commit-limit` functionality works as expected then we can close the issue.

**Comment by rgburke** [comment]
Closing this as the functionality is implemented. Please raise any bugs as new issues.
