### ISSUE TITLE
initial layout

### ISSUE THREAD

**Issue by mckellyln** [rgburke/grv#91]
Hi,

Is there a way (with default-view perhaps ?) to change the initial layout of windows when grv starts ?
What would default-view be set to, to get:
Refs to be less rows
Remotes to be more rows
And then Commits Window on top of Diff window

thx as always for grv,
-m

**Comment by rgburke** [comment]
Thanks for raising this. At the moment it's not possible to change the view layout in the way you would like. The splits always default to an equal amount of space for each child view. The `History View` has some hard coded logic in order for it to display as it currently does.

I think this is a nice idea and one of the things I wanted was for GRV to be configurable. It should be possible to update the `split` commands to accept widths/heights/percentages so that the `default-view` functionality can be used to create a customized `History View`. I will have a look into implementing this.

**Comment by mckellyln** [comment]
Closing as its been a while.
Thank you for grv.
